---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

library(dplyr)
library(lattice)

df<-read.csv("activity.csv", header=TRUE)

#Removes missing value from original dataframe
df1<-filter(df, !is.na(steps))


## What is mean total number of steps taken per day?

#Sorting and adding total steps taken each day. 
stepperday<-group_by(df1,date)
totalstep<-summarise(stepperday, totalstepperday=sum(steps))

with(totalstep, hist(totalstepperday,xlab="Total Steps Per Day", main="Histogram of Total Steps Taken Each Day", col="blue"))

mean(totalstep$totalstepperday)
median(totalstep$totalstepperday)

## What is the average daily activity pattern?

dailyactivity<-aggregate(steps~interval, data=df, mean, na.rm=T)
names(dailyactivity)<-c("interval", "avg_step")

with(dailyactivity, plot(x=interval, y=avg_step, type="l", col="blue", ylab="Avg Steps Taken, Averaged Across all Days", main="Daily Activity Pattern"))

dailyactivity[which.max(dailyactivity$avg_step), ]$interval

## Imputing missing values

#counting the total number of missing step values.
sum(is.na(df))
#Merging the original dataframe with the dataframes for averages of the 5 minute intervals.
combineddf<-merge(dailyactivity, df)
#Subsetting only the NA rows and for steps and replacing them with the averages for that 5 #minute interval.  Placing the imputed data into a new column labeled "step"
combineddf$step[is.na(combineddf$steps)]<-combineddf$avg_step[is.na(combineddf$steps)]


imputedstepperday<-combineddf%>% group_by(date) %>% summarise(totalstepperday= sum(step))
with(imputedstepperday, hist(totalstepperday,xlab="Total Steps Per Day", main="Histogram of Total Steps Taken Each Day", col="blue"))

mean(imputedstepperday$totalstepperday)
median(imputedstepperday$totalstepperday)

## Are there differences in activity patterns between weekdays and weekends?

#Added two additional columns "day" and "day_type" to define the day of the week then
#to categorize which is weekend and weekday using the ifelse statement.
combineddf$day<-weekdays(as.Date(combineddf$date))
combineddf$day_type<-ifelse (combineddf$day %in% c("Saturday", "Sunday"), "weekend", "weekday")

weekactivity<-combineddf%>% group_by(interval, day_type) %>% summarise(avg_stepperday= mean(step))

with(weekactivity, xyplot(avg_stepperday ~ interval | factor(day_type), layout = c(1,2), type = "l", col="blue"))

